services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - bloghive-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - bloghive-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093' # Required for new versions
      KAFKA_NODE_ID: 1                               # Required for new versions
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'  # Required for new versions
      CLUSTER_ID: 'SGc8NYJASB2am0JOKNEb_g'           # The critical missing piece
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  mysql:
    image: mysql:8.0
    networks:
      - bloghive-net
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: vistaar07/eureka-server
    restart: on-failure
    ports:
      - "8761:8761"
    networks:
      - bloghive-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
      
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: vistaar07/config-server
    ports:
      - "8888:8888"
    networks:
      - bloghive-net
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: vistaar07/api-gateway
    ports:
      - "8080:8080"
    networks:
      - bloghive-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: vistaar07/auth-service
    ports:
      - "9001:9001"
    networks:
      - bloghive-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
      mysql:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/authdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    image: vistaar07/post-service
    ports:
      - "9002:9002"
    networks:
      - bloghive-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
      mysql:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/postdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    image: vistaar07/comment-service
    ports:
      - "9003:9003"
    networks:
      - bloghive-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
      mysql:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/commentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: vistaar07/notification-service
    ports:
      - "9004:9004"
    networks:
      - bloghive-net
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
      mysql:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/notificationdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

networks:
  bloghive-net:
    driver: bridge