apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bloghive
spec:
  selector:
    app: blog-hive
  ports:
    - protocol: TCP
      port: 3000      # <-- CHANGED
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: bloghive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-hive
  template:
    metadata:
      labels:
        app: blog-hive
    spec:
      containers:
        - name: blog-hive
          image: ammare03/blog-hive:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://api-gateway-service:80"