server.port=8888
spring.application.name=config-server

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Git repository for configuration files
spring.cloud.config.server.git.uri=https://github.com/ammare03/BlogHive

# Sub-dir for config files
spring.cloud.config.server.git.search-paths=config-files